package com.link.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_channel", "id", Channel.class);
		arp.addMapping("t_content", "id", Content.class);
		arp.addMapping("t_log", "id", Log.class);
		arp.addMapping("t_menu", "id", Menu.class);
		arp.addMapping("t_org", "id", Org.class);
		arp.addMapping("t_permission", "id", Permission.class);
		arp.addMapping("t_role", "id", Role.class);
		arp.addMapping("t_role_menu", "id", RoleMenu.class);
		arp.addMapping("t_role_permission", "id", RolePermission.class);
		arp.addMapping("t_user", "id", User.class);
		arp.addMapping("t_user_org", "id", UserOrg.class);
		arp.addMapping("t_user_role", "id", UserRole.class);
	}
}

