package com.link.model;

import com.link.model.base.BaseChannel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Channel extends BaseChannel<Channel> {
	public static final Channel dao = new Channel().dao();
}
