package com.link.model;

import com.link.model.base.BaseChsi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Chsi extends BaseChsi<Chsi> {
	public static final Chsi dao = new Chsi().dao();
}
