package com.link.model;

import com.link.model.base.BaseOrg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Org extends BaseOrg<Org> {
	public static final Org dao = new Org().dao();
}
