package com.link.model;

import com.link.model.base.BaseUserOrg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserOrg extends BaseUserOrg<UserOrg> {
	public static final UserOrg dao = new UserOrg().dao();
}
