package com.link.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChsi<M extends BaseChsi<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return getStr("sex");
	}

	public void setBirthday(java.lang.String birthday) {
		set("birthday", birthday);
	}

	public java.lang.String getBirthday() {
		return getStr("birthday");
	}

	public void setNation(java.lang.String nation) {
		set("nation", nation);
	}

	public java.lang.String getNation() {
		return getStr("nation");
	}

	public void setCardno(java.lang.String cardno) {
		set("cardno", cardno);
	}

	public java.lang.String getCardno() {
		return getStr("cardno");
	}

	public void setSchoolName(java.lang.String schoolName) {
		set("schoolName", schoolName);
	}

	public java.lang.String getSchoolName() {
		return getStr("schoolName");
	}

	public void setSchoolLevel(java.lang.String schoolLevel) {
		set("schoolLevel", schoolLevel);
	}

	public java.lang.String getSchoolLevel() {
		return getStr("schoolLevel");
	}

	public void setProfessional(java.lang.String professional) {
		set("professional", professional);
	}

	public java.lang.String getProfessional() {
		return getStr("professional");
	}

	public void setLengthOfSchooling(java.lang.String lengthOfSchooling) {
		set("lengthOfSchooling", lengthOfSchooling);
	}

	public java.lang.String getLengthOfSchooling() {
		return getStr("lengthOfSchooling");
	}

	public void setCategory(java.lang.String category) {
		set("category", category);
	}

	public java.lang.String getCategory() {
		return getStr("category");
	}

	public void setSchool(java.lang.String school) {
		set("school", school);
	}

	public java.lang.String getSchool() {
		return getStr("school");
	}

	public void setDepartment(java.lang.String department) {
		set("department", department);
	}

	public java.lang.String getDepartment() {
		return getStr("department");
	}

	public void setClasses(java.lang.String classes) {
		set("classes", classes);
	}

	public java.lang.String getClasses() {
		return getStr("classes");
	}

	public void setStudentno(java.lang.String studentno) {
		set("studentno", studentno);
	}

	public java.lang.String getStudentno() {
		return getStr("studentno");
	}

	public void setInSchool(java.lang.String inSchool) {
		set("inSchool", inSchool);
	}

	public java.lang.String getInSchool() {
		return getStr("inSchool");
	}

	public void setOutSchool(java.lang.String outSchool) {
		set("outSchool", outSchool);
	}

	public java.lang.String getOutSchool() {
		return getStr("outSchool");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

}
