package com.link.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrg<M extends BaseOrg<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setComcode(java.lang.String comcode) {
		set("comcode", comcode);
	}

	public java.lang.String getComcode() {
		return getStr("comcode");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return getStr("type");
	}

	public void setSortno(java.lang.Integer sortno) {
		set("sortno", sortno);
	}

	public java.lang.Integer getSortno() {
		return getInt("sortno");
	}

	public void setDesciption(java.lang.String desciption) {
		set("desciption", desciption);
	}

	public java.lang.String getDesciption() {
		return getStr("desciption");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setPid(java.lang.String pid) {
		set("pid", pid);
	}

	public java.lang.String getPid() {
		return getStr("pid");
	}

}
