package com.link.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}

	public java.lang.String getValue() {
		return getStr("value");
	}

	public void setIntro(java.lang.String intro) {
		set("intro", intro);
	}

	public java.lang.String getIntro() {
		return getStr("intro");
	}

	public void setPid(java.lang.String pid) {
		set("pid", pid);
	}

	public java.lang.String getPid() {
		return getStr("pid");
	}

	public void setCreatedAt(java.lang.String createdAt) {
		set("created_at", createdAt);
	}

	public java.lang.String getCreatedAt() {
		return getStr("created_at");
	}

	public void setUpdatedAt(java.lang.String updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.lang.String getUpdatedAt() {
		return getStr("updated_at");
	}

	public void setDeletedAt(java.lang.String deletedAt) {
		set("deleted_at", deletedAt);
	}

	public java.lang.String getDeletedAt() {
		return getStr("deleted_at");
	}

}
